### ISSUE TITLE
Size info on complete message

### ISSUE THREAD

**Issue by devfubar** [hevnly/image-resizer#7]
After the resizing is complete an event is fired off either to an HTTP call or an SQS.  This should contain information about which sizes were produced, perhaps very similar to the configuration json that defines what copies are to be made ie

```
 { "width": 800, "height": 800, "name": "large" },
 { "width": 500, "height": 500, "name": "medium" },
 { "width": 200, "height": 200, "name": "small" },
 { "width": 45, "height": 45, "name": "thumbnail"}
```

**Comment by hyprstack** [comment]
Done.
